// Generated by scripts/generate-game-data.mjs — do not edit.
import type { Job } from '@/types/game'

export const JOBS: readonly Job[] = [
  { id: 26, name: 'Alchemist' },
  { id: 60, name: 'Artificer' },
  { id: 1, name: 'Base' },
  { id: 79, name: 'Breeder' },
  { id: 13, name: 'Carver' },
  { id: 28, name: 'Farmer' },
  { id: 36, name: 'Fisherman' },
  { id: 65, name: 'Handyman' },
  { id: 41, name: 'Hunter' },
  { id: 16, name: 'Jeweller' },
  { id: 2, name: 'Lumberjack' },
  { id: 24, name: 'Miner' },
  { id: 15, name: 'Shoemaker' },
  { id: 11, name: 'Smith' },
  { id: 27, name: 'Tailor' },
]
