// Generated by scripts/generate-game-data.mjs — do not edit.
import type { Server } from '@/types/game'

export const SERVERS: readonly Server[] = [
  { id: 351, name: 'Brial' },
  { id: 353, name: 'Dakal' },
  { id: 295, name: 'Draconiros' },
  { id: 294, name: 'Hell Mina' },
  { id: 291, name: 'Imagiro' },
  { id: 355, name: 'Kourial' },
  { id: 354, name: 'Mikhal' },
  { id: 292, name: 'Orukam' },
  { id: 350, name: 'Rafal' },
  { id: 352, name: 'Salar' },
  { id: 800, name: 'Shukrute' },
  { id: 290, name: 'Tal Kasha' },
  { id: 293, name: 'Tylezia' },
]

export const DEFAULT_SERVER_ID = 355
